CREATE TABLE ALUNO ( 
    MATRICULA INT,
    NOME VARCHAR(45),
    CPF INT,
    IDENTIDADE VARCHAR(20),
    TELEFONE INT
);
CREATE TABLE FAMILIARES_ALUNO (
    MATRICULA INT,
    NOME_FAMILIAR VARCHAR(45),
    GRAU_PARENTESCO VARCHAR(10),
    VINCULO_EMPREGATICIO BOOLEAN,
    RENDA MENSAL MONEY
);
CREATE TABLE ENDERECO (
    MATRICULA INT,
    RUA VARCHAR(45),
    NUMERO INT,
    CIDADE VARCHAR(45),
    ESTADO VARCHAR(45)
);
CREATE TABLE EVASAO_QUADRO_DE_ATIVIDADES (
    MATRICULA INT,
    SEGUNDA_MANHA VARCHAR(45),
    SEGUNDA_TARDE VARCHAR(45),
    SEGUNDA_NOITE VARCHAR(45),
    TERCA_MANHA VARCHAR(45),
    TERCA_TARDE VARCHAR(45),
    TERCA_NOITE VARCHAR(45),
    QUARTA_MANHA VARCHAR(45),
    QUARTA_TARDE VARCHAR(45),
    QUARTA_NOITE VARCHAR(45),
    QUINTA_MANHA VARCHAR(45),
    QUINTA_TARDE VARCHAR(45),
    QUINTA_NOITE VARCHAR(45),
    SEXTA_MANHA VARCHAR(45),
    SEXTA_TARDE VARCHAR(45),
    SEXTA_NOITE VARCHAR(45),
    SABADO_MANHA VARCHAR(45),
    SABADO_TARDE VARCHAR(45),
    SABADO_NOITE VARCHAR(45), 
    DOMINGO_MANHA VARCHAR(45),
    DOMINGO_TARDE VARCHAR(45),
    DOMINGO_NOITE VARCHAR(45)
);
CREATE TABLE EVASAO_DIFICULDADES (
	MATRICULA INT,
    DISCIPLINA VARCHAR(45),
    DIFICULDADES VARCHAR (45)
);
CREATE TABLE ASSISTENCIA_TRANSPORTE_MODALIDADE_PRETENDIDA (
    MATRICULA INT,
    TIPO VARCHAR(45)
);
CREATE TABLE ASSISTENCIA (
	MATRICULA INT,
    DOCUMENTACAO BLOB
);    
CREATE TABLE ASSISTENCIA_AUXILIOS (
    MATRICULA INT,
    ALIMENTACAO BOOLEAN,
    TRANSPORTE BOOLEAN,
    MORADIA BOOLEAN,
    DIDATICO BOOLEAN
);
CREATE TABLE ASSISTENCIA_ALUNOS_PENDENCIA_DOCUMENTOS (
	MATRICULA INT,
	DOCUMENTO_PENDENTE VARCHAR(45)
); 